version: "3"
services:
  server:
    container_name: "server"
    build: ./server/
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: npm run dev
    volumes:
      - ${PWD}/server:/usr/src/app
      - /usr/src/app/node_modules/

  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ${PWD}/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  client:
    container_name: "client"
    build: ./client/
    depends_on:
      - server
    ports:
      - "3002:3000"
    stdin_open: true
    command: npm start
    volumes:
      - ${PWD}/client:/usr/src/app
      - /usr/src/app/node_modules/
